/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Assessment = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'updatedAt' : Time,
  'currentStep' : IDL.Text,
});
export const PracticeRating = IDL.Record({
  'id' : IDL.Nat,
  'weaknesses' : IDL.Text,
  'strengths' : IDL.Text,
  'workProductsInspected' : IDL.Text,
  'level' : IDL.Nat,
  'rating' : IDL.Text,
  'assessmentId' : IDL.Nat,
  'processId' : IDL.Text,
  'practiceId' : IDL.Text,
});
export const AssessmentDay = IDL.Record({
  'id' : IDL.Nat,
  'timeTo' : IDL.Text,
  'date' : IDL.Text,
  'dayNumber' : IDL.Nat,
  'sessions' : IDL.Text,
  'assessmentId' : IDL.Nat,
  'timeFrom' : IDL.Text,
});
export const AssessmentInfoData = IDL.Record({
  'unitDepartment' : IDL.Text,
  'projectName' : IDL.Text,
  'endDate' : IDL.Text,
  'agileEnvironments' : IDL.Bool,
  'modelBasedDev' : IDL.Bool,
  'additionalRemarks' : IDL.Text,
  'cybersecurityLevel' : IDL.Text,
  'coAssessor' : IDL.Text,
  'leadAssessor' : IDL.Text,
  'projectContactSWQuality' : IDL.Text,
  'sponsor' : IDL.Text,
  'pamVersion' : IDL.Text,
  'developmentExternal' : IDL.Bool,
  'projectContactSWDev' : IDL.Text,
  'assessmentId' : IDL.Nat,
  'intacsId' : IDL.Text,
  'functionalSafetyLevel' : IDL.Text,
  'assessedParty' : IDL.Text,
  'assessmentClass' : IDL.Text,
  'projectScope' : IDL.Text,
  'targetCapabilityLevel' : IDL.Text,
  'assessedSite' : IDL.Text,
  'assessorBody' : IDL.Text,
  'startDate' : IDL.Text,
  'vdaVersion' : IDL.Text,
});
export const ProcessGroupConfig = IDL.Record({
  'enabledGroups' : IDL.Text,
  'processLevels' : IDL.Text,
  'assessmentId' : IDL.Nat,
});

export const idlService = IDL.Service({
  'createAssessment' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'deleteAssessment' : IDL.Func([IDL.Nat], [], []),
  'deleteAssessmentDay' : IDL.Func([IDL.Nat], [], []),
  'getAllAssessments' : IDL.Func([], [IDL.Vec(Assessment)], ['query']),
  'getAllPracticeRatingsForAssessment' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(PracticeRating)],
      ['query'],
    ),
  'getAssessment' : IDL.Func([IDL.Nat], [Assessment], ['query']),
  'getAssessmentDays' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(AssessmentDay)],
      ['query'],
    ),
  'getAssessmentInfoData' : IDL.Func(
      [IDL.Nat],
      [AssessmentInfoData],
      ['query'],
    ),
  'getPracticeRatings' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Vec(PracticeRating)],
      ['query'],
    ),
  'getProcessGroupConfig' : IDL.Func(
      [IDL.Nat],
      [ProcessGroupConfig],
      ['query'],
    ),
  'markAssessmentCompleted' : IDL.Func([IDL.Nat], [], []),
  'saveAssessmentDay' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'saveAssessmentInfoData' : IDL.Func([AssessmentInfoData], [], []),
  'savePracticeRating' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'saveProcessGroupConfig' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'updateAssessmentStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateAssessmentStep' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Assessment = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'updatedAt' : Time,
    'currentStep' : IDL.Text,
  });
  const PracticeRating = IDL.Record({
    'id' : IDL.Nat,
    'weaknesses' : IDL.Text,
    'strengths' : IDL.Text,
    'workProductsInspected' : IDL.Text,
    'level' : IDL.Nat,
    'rating' : IDL.Text,
    'assessmentId' : IDL.Nat,
    'processId' : IDL.Text,
    'practiceId' : IDL.Text,
  });
  const AssessmentDay = IDL.Record({
    'id' : IDL.Nat,
    'timeTo' : IDL.Text,
    'date' : IDL.Text,
    'dayNumber' : IDL.Nat,
    'sessions' : IDL.Text,
    'assessmentId' : IDL.Nat,
    'timeFrom' : IDL.Text,
  });
  const AssessmentInfoData = IDL.Record({
    'unitDepartment' : IDL.Text,
    'projectName' : IDL.Text,
    'endDate' : IDL.Text,
    'agileEnvironments' : IDL.Bool,
    'modelBasedDev' : IDL.Bool,
    'additionalRemarks' : IDL.Text,
    'cybersecurityLevel' : IDL.Text,
    'coAssessor' : IDL.Text,
    'leadAssessor' : IDL.Text,
    'projectContactSWQuality' : IDL.Text,
    'sponsor' : IDL.Text,
    'pamVersion' : IDL.Text,
    'developmentExternal' : IDL.Bool,
    'projectContactSWDev' : IDL.Text,
    'assessmentId' : IDL.Nat,
    'intacsId' : IDL.Text,
    'functionalSafetyLevel' : IDL.Text,
    'assessedParty' : IDL.Text,
    'assessmentClass' : IDL.Text,
    'projectScope' : IDL.Text,
    'targetCapabilityLevel' : IDL.Text,
    'assessedSite' : IDL.Text,
    'assessorBody' : IDL.Text,
    'startDate' : IDL.Text,
    'vdaVersion' : IDL.Text,
  });
  const ProcessGroupConfig = IDL.Record({
    'enabledGroups' : IDL.Text,
    'processLevels' : IDL.Text,
    'assessmentId' : IDL.Nat,
  });
  
  return IDL.Service({
    'createAssessment' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'deleteAssessment' : IDL.Func([IDL.Nat], [], []),
    'deleteAssessmentDay' : IDL.Func([IDL.Nat], [], []),
    'getAllAssessments' : IDL.Func([], [IDL.Vec(Assessment)], ['query']),
    'getAllPracticeRatingsForAssessment' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(PracticeRating)],
        ['query'],
      ),
    'getAssessment' : IDL.Func([IDL.Nat], [Assessment], ['query']),
    'getAssessmentDays' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(AssessmentDay)],
        ['query'],
      ),
    'getAssessmentInfoData' : IDL.Func(
        [IDL.Nat],
        [AssessmentInfoData],
        ['query'],
      ),
    'getPracticeRatings' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Vec(PracticeRating)],
        ['query'],
      ),
    'getProcessGroupConfig' : IDL.Func(
        [IDL.Nat],
        [ProcessGroupConfig],
        ['query'],
      ),
    'markAssessmentCompleted' : IDL.Func([IDL.Nat], [], []),
    'saveAssessmentDay' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'saveAssessmentInfoData' : IDL.Func([AssessmentInfoData], [], []),
    'savePracticeRating' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'saveProcessGroupConfig' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'updateAssessmentStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateAssessmentStep' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };