/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const AssessmentPlan = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'scheduledDate' : Time,
  'planDetails' : IDL.Text,
  'assessmentId' : IDL.Nat,
});
export const AssessmentResult = IDL.Record({
  'id' : IDL.Nat,
  'completedAt' : Time,
  'recommendations' : IDL.Text,
  'score' : IDL.Nat,
  'findings' : IDL.Text,
  'assessmentId' : IDL.Nat,
});
export const Assessment = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
});
export const Report = IDL.Record({
  'id' : IDL.Nat,
  'generatedAt' : Time,
  'reportContent' : IDL.Text,
  'assessmentId' : IDL.Nat,
});
export const TargetProfile = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'criteria' : IDL.Text,
  'skillLevel' : IDL.Text,
  'assessmentId' : IDL.Nat,
});
export const WorkProduct = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'fileType' : IDL.Text,
  'notes' : IDL.Text,
  'assessmentId' : IDL.Nat,
  'uploadedAt' : Time,
});

export const idlService = IDL.Service({
  'addAssessmentResult' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addWorkProduct' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createAssessment' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'createAssessmentPlan' : IDL.Func(
      [IDL.Nat, IDL.Text, Time, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createTargetProfile' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteAssessment' : IDL.Func([IDL.Nat], [], []),
  'generateReport' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'getAllAssessmentPlans' : IDL.Func([], [IDL.Vec(AssessmentPlan)], ['query']),
  'getAllAssessmentResults' : IDL.Func(
      [],
      [IDL.Vec(AssessmentResult)],
      ['query'],
    ),
  'getAllAssessments' : IDL.Func([], [IDL.Vec(Assessment)], ['query']),
  'getAllReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
  'getAllTargetProfiles' : IDL.Func([], [IDL.Vec(TargetProfile)], ['query']),
  'getAllWorkProducts' : IDL.Func([], [IDL.Vec(WorkProduct)], ['query']),
  'getAssessment' : IDL.Func([IDL.Nat], [Assessment], ['query']),
  'getAssessmentPlan' : IDL.Func([IDL.Nat], [AssessmentPlan], ['query']),
  'getAssessmentResult' : IDL.Func([IDL.Nat], [AssessmentResult], ['query']),
  'getReport' : IDL.Func([IDL.Nat], [Report], ['query']),
  'getTargetProfile' : IDL.Func([IDL.Nat], [TargetProfile], ['query']),
  'getWorkProduct' : IDL.Func([IDL.Nat], [WorkProduct], ['query']),
  'updateAssessment' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const AssessmentPlan = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'scheduledDate' : Time,
    'planDetails' : IDL.Text,
    'assessmentId' : IDL.Nat,
  });
  const AssessmentResult = IDL.Record({
    'id' : IDL.Nat,
    'completedAt' : Time,
    'recommendations' : IDL.Text,
    'score' : IDL.Nat,
    'findings' : IDL.Text,
    'assessmentId' : IDL.Nat,
  });
  const Assessment = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
  });
  const Report = IDL.Record({
    'id' : IDL.Nat,
    'generatedAt' : Time,
    'reportContent' : IDL.Text,
    'assessmentId' : IDL.Nat,
  });
  const TargetProfile = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'criteria' : IDL.Text,
    'skillLevel' : IDL.Text,
    'assessmentId' : IDL.Nat,
  });
  const WorkProduct = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'fileType' : IDL.Text,
    'notes' : IDL.Text,
    'assessmentId' : IDL.Nat,
    'uploadedAt' : Time,
  });
  
  return IDL.Service({
    'addAssessmentResult' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addWorkProduct' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createAssessment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createAssessmentPlan' : IDL.Func(
        [IDL.Nat, IDL.Text, Time, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createTargetProfile' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteAssessment' : IDL.Func([IDL.Nat], [], []),
    'generateReport' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'getAllAssessmentPlans' : IDL.Func(
        [],
        [IDL.Vec(AssessmentPlan)],
        ['query'],
      ),
    'getAllAssessmentResults' : IDL.Func(
        [],
        [IDL.Vec(AssessmentResult)],
        ['query'],
      ),
    'getAllAssessments' : IDL.Func([], [IDL.Vec(Assessment)], ['query']),
    'getAllReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
    'getAllTargetProfiles' : IDL.Func([], [IDL.Vec(TargetProfile)], ['query']),
    'getAllWorkProducts' : IDL.Func([], [IDL.Vec(WorkProduct)], ['query']),
    'getAssessment' : IDL.Func([IDL.Nat], [Assessment], ['query']),
    'getAssessmentPlan' : IDL.Func([IDL.Nat], [AssessmentPlan], ['query']),
    'getAssessmentResult' : IDL.Func([IDL.Nat], [AssessmentResult], ['query']),
    'getReport' : IDL.Func([IDL.Nat], [Report], ['query']),
    'getTargetProfile' : IDL.Func([IDL.Nat], [TargetProfile], ['query']),
    'getWorkProduct' : IDL.Func([IDL.Nat], [WorkProduct], ['query']),
    'updateAssessment' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };