/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Assessment {
  'id' : bigint,
  'status' : string,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
}
export interface AssessmentPlan {
  'id' : bigint,
  'status' : string,
  'scheduledDate' : Time,
  'planDetails' : string,
  'assessmentId' : bigint,
}
export interface AssessmentResult {
  'id' : bigint,
  'completedAt' : Time,
  'recommendations' : string,
  'score' : bigint,
  'findings' : string,
  'assessmentId' : bigint,
}
export interface Report {
  'id' : bigint,
  'generatedAt' : Time,
  'reportContent' : string,
  'assessmentId' : bigint,
}
export interface TargetProfile {
  'id' : bigint,
  'name' : string,
  'criteria' : string,
  'skillLevel' : string,
  'assessmentId' : bigint,
}
export type Time = bigint;
export interface WorkProduct {
  'id' : bigint,
  'name' : string,
  'fileType' : string,
  'notes' : string,
  'assessmentId' : bigint,
  'uploadedAt' : Time,
}
export interface _SERVICE {
  'addAssessmentResult' : ActorMethod<[bigint, bigint, string, string], bigint>,
  'addWorkProduct' : ActorMethod<[bigint, string, string, string], bigint>,
  'createAssessment' : ActorMethod<[string, string, string], bigint>,
  'createAssessmentPlan' : ActorMethod<[bigint, string, Time, string], bigint>,
  'createTargetProfile' : ActorMethod<[bigint, string, string, string], bigint>,
  'deleteAssessment' : ActorMethod<[bigint], undefined>,
  'generateReport' : ActorMethod<[bigint, string], bigint>,
  'getAllAssessmentPlans' : ActorMethod<[], Array<AssessmentPlan>>,
  'getAllAssessmentResults' : ActorMethod<[], Array<AssessmentResult>>,
  'getAllAssessments' : ActorMethod<[], Array<Assessment>>,
  'getAllReports' : ActorMethod<[], Array<Report>>,
  'getAllTargetProfiles' : ActorMethod<[], Array<TargetProfile>>,
  'getAllWorkProducts' : ActorMethod<[], Array<WorkProduct>>,
  'getAssessment' : ActorMethod<[bigint], Assessment>,
  'getAssessmentPlan' : ActorMethod<[bigint], AssessmentPlan>,
  'getAssessmentResult' : ActorMethod<[bigint], AssessmentResult>,
  'getReport' : ActorMethod<[bigint], Report>,
  'getTargetProfile' : ActorMethod<[bigint], TargetProfile>,
  'getWorkProduct' : ActorMethod<[bigint], WorkProduct>,
  'updateAssessment' : ActorMethod<[bigint, string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];