/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Assessment {
  'id' : bigint,
  'status' : string,
  'name' : string,
  'createdAt' : Time,
  'updatedAt' : Time,
  'currentStep' : string,
}
export interface AssessmentDay {
  'id' : bigint,
  'timeTo' : string,
  'date' : string,
  'dayNumber' : bigint,
  'sessions' : string,
  'assessmentId' : bigint,
  'timeFrom' : string,
}
export interface AssessmentInfoData {
  'unitDepartment' : string,
  'projectName' : string,
  'endDate' : string,
  'agileEnvironments' : boolean,
  'modelBasedDev' : boolean,
  'additionalRemarks' : string,
  'cybersecurityLevel' : string,
  'coAssessor' : string,
  'leadAssessor' : string,
  'projectContactSWQuality' : string,
  'sponsor' : string,
  'pamVersion' : string,
  'developmentExternal' : boolean,
  'projectContactSWDev' : string,
  'assessmentId' : bigint,
  'intacsId' : string,
  'functionalSafetyLevel' : string,
  'assessedParty' : string,
  'assessmentClass' : string,
  'projectScope' : string,
  'targetCapabilityLevel' : string,
  'assessedSite' : string,
  'assessorBody' : string,
  'startDate' : string,
  'vdaVersion' : string,
}
export interface PracticeRating {
  'id' : bigint,
  'weaknesses' : string,
  'strengths' : string,
  'workProductsInspected' : string,
  'level' : bigint,
  'rating' : string,
  'assessmentId' : bigint,
  'processId' : string,
  'practiceId' : string,
}
export interface ProcessGroupConfig {
  'enabledGroups' : string,
  'processLevels' : string,
  'assessmentId' : bigint,
}
export type Time = bigint;
export interface _SERVICE {
  'createAssessment' : ActorMethod<[string], bigint>,
  'deleteAssessmentDay' : ActorMethod<[bigint], undefined>,
  'getAllAssessments' : ActorMethod<[], Array<Assessment>>,
  'getAllPracticeRatingsForAssessment' : ActorMethod<
    [bigint],
    Array<PracticeRating>
  >,
  'getAssessment' : ActorMethod<[bigint], Assessment>,
  'getAssessmentDays' : ActorMethod<[bigint], Array<AssessmentDay>>,
  'getAssessmentInfoData' : ActorMethod<[bigint], AssessmentInfoData>,
  'getPracticeRatings' : ActorMethod<[bigint, string], Array<PracticeRating>>,
  'getProcessGroupConfig' : ActorMethod<[bigint], ProcessGroupConfig>,
  'markAssessmentCompleted' : ActorMethod<[bigint], undefined>,
  'saveAssessmentDay' : ActorMethod<
    [bigint, bigint, string, string, string, string],
    bigint
  >,
  'saveAssessmentInfoData' : ActorMethod<[AssessmentInfoData], undefined>,
  'savePracticeRating' : ActorMethod<
    [bigint, string, bigint, string, string, string, string, string],
    bigint
  >,
  'saveProcessGroupConfig' : ActorMethod<[bigint, string, string], undefined>,
  'updateAssessmentStatus' : ActorMethod<[bigint, string], undefined>,
  'updateAssessmentStep' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];