/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AssessmentDay {
    id: bigint;
    timeTo: string;
    date: string;
    dayNumber: bigint;
    sessions: string;
    assessmentId: bigint;
    timeFrom: string;
}
export type Time = bigint;
export interface Assessment {
    id: bigint;
    status: string;
    name: string;
    createdAt: Time;
    updatedAt: Time;
    currentStep: string;
}
export interface PracticeRating {
    id: bigint;
    weaknesses: string;
    strengths: string;
    workProductsInspected: string;
    level: bigint;
    rating: string;
    assessmentId: bigint;
    processId: string;
    practiceId: string;
}
export interface ProcessGroupConfig {
    enabledGroups: string;
    processLevels: string;
    assessmentId: bigint;
}
export interface AssessmentInfoData {
    unitDepartment: string;
    projectName: string;
    endDate: string;
    agileEnvironments: boolean;
    modelBasedDev: boolean;
    additionalRemarks: string;
    cybersecurityLevel: string;
    coAssessor: string;
    leadAssessor: string;
    projectContactSWQuality: string;
    sponsor: string;
    pamVersion: string;
    developmentExternal: boolean;
    projectContactSWDev: string;
    assessmentId: bigint;
    intacsId: string;
    functionalSafetyLevel: string;
    assessedParty: string;
    assessmentClass: string;
    projectScope: string;
    targetCapabilityLevel: string;
    assessedSite: string;
    assessorBody: string;
    startDate: string;
    vdaVersion: string;
}
export interface ProjectEvidence {
    id: bigint;
    link: string;
    name: string;
    version: string;
    assessmentId: bigint;
    processId: string;
}
export interface ReportGlobalInputs {
    globalStrengths: string;
    globalWeaknesses: string;
    assessmentId: bigint;
}
export interface backendInterface {
    addProjectEvidence(assessmentId: bigint, processId: string, name: string, link: string, version: string): Promise<bigint>;
    createAssessment(name: string): Promise<bigint>;
    deleteAssessment(id: bigint): Promise<void>;
    deleteAssessmentDay(id: bigint): Promise<void>;
    deleteProjectEvidence(id: bigint): Promise<boolean>;
    getAllAssessments(): Promise<Array<Assessment>>;
    getAllPracticeRatingsForAssessment(assessmentId: bigint): Promise<Array<PracticeRating>>;
    getAssessment(id: bigint): Promise<Assessment>;
    getAssessmentDays(assessmentId: bigint): Promise<Array<AssessmentDay>>;
    getAssessmentInfoData(assessmentId: bigint): Promise<AssessmentInfoData>;
    getPracticeRatings(assessmentId: bigint, processId: string): Promise<Array<PracticeRating>>;
    getProcessGroupConfig(assessmentId: bigint): Promise<ProcessGroupConfig>;
    getProjectEvidenceForAssessment(assessmentId: bigint): Promise<Array<ProjectEvidence>>;
    getReportGlobalInputs(assessmentId: bigint): Promise<ReportGlobalInputs>;
    markAssessmentCompleted(id: bigint): Promise<void>;
    saveAssessmentDay(assessmentId: bigint, dayNumber: bigint, date: string, timeFrom: string, timeTo: string, sessions: string): Promise<bigint>;
    saveAssessmentInfoData(data: AssessmentInfoData): Promise<void>;
    savePracticeRating(assessmentId: bigint, processId: string, level: bigint, practiceId: string, rating: string, strengths: string, weaknesses: string, workProductsInspected: string): Promise<bigint>;
    saveProcessGroupConfig(assessmentId: bigint, enabledGroups: string, processLevels: string): Promise<void>;
    saveReportGlobalInputs(assessmentId: bigint, globalStrengths: string, globalWeaknesses: string): Promise<void>;
    updateAssessmentStatus(id: bigint, status: string): Promise<void>;
    updateAssessmentStep(id: bigint, step: string): Promise<void>;
    updateProjectEvidence(id: bigint, processId: string, name: string, link: string, version: string): Promise<boolean>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addProjectEvidence(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addProjectEvidence(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProjectEvidence(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createAssessment(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createAssessment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAssessment(arg0);
            return result;
        }
    }
    async deleteAssessment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAssessment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAssessment(arg0);
            return result;
        }
    }
    async deleteAssessmentDay(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAssessmentDay(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAssessmentDay(arg0);
            return result;
        }
    }
    async deleteProjectEvidence(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProjectEvidence(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProjectEvidence(arg0);
            return result;
        }
    }
    async getAllAssessments(): Promise<Array<Assessment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAssessments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAssessments();
            return result;
        }
    }
    async getAllPracticeRatingsForAssessment(arg0: bigint): Promise<Array<PracticeRating>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPracticeRatingsForAssessment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPracticeRatingsForAssessment(arg0);
            return result;
        }
    }
    async getAssessment(arg0: bigint): Promise<Assessment> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssessment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssessment(arg0);
            return result;
        }
    }
    async getAssessmentDays(arg0: bigint): Promise<Array<AssessmentDay>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssessmentDays(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssessmentDays(arg0);
            return result;
        }
    }
    async getAssessmentInfoData(arg0: bigint): Promise<AssessmentInfoData> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssessmentInfoData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssessmentInfoData(arg0);
            return result;
        }
    }
    async getPracticeRatings(arg0: bigint, arg1: string): Promise<Array<PracticeRating>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPracticeRatings(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPracticeRatings(arg0, arg1);
            return result;
        }
    }
    async getProcessGroupConfig(arg0: bigint): Promise<ProcessGroupConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getProcessGroupConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProcessGroupConfig(arg0);
            return result;
        }
    }
    async getProjectEvidenceForAssessment(arg0: bigint): Promise<Array<ProjectEvidence>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjectEvidenceForAssessment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjectEvidenceForAssessment(arg0);
            return result;
        }
    }
    async getReportGlobalInputs(arg0: bigint): Promise<ReportGlobalInputs> {
        if (this.processError) {
            try {
                const result = await this.actor.getReportGlobalInputs(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReportGlobalInputs(arg0);
            return result;
        }
    }
    async markAssessmentCompleted(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAssessmentCompleted(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAssessmentCompleted(arg0);
            return result;
        }
    }
    async saveAssessmentDay(arg0: bigint, arg1: bigint, arg2: string, arg3: string, arg4: string, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.saveAssessmentDay(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveAssessmentDay(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async saveAssessmentInfoData(arg0: AssessmentInfoData): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveAssessmentInfoData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveAssessmentInfoData(arg0);
            return result;
        }
    }
    async savePracticeRating(arg0: bigint, arg1: string, arg2: bigint, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.savePracticeRating(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePracticeRating(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async saveProcessGroupConfig(arg0: bigint, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveProcessGroupConfig(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveProcessGroupConfig(arg0, arg1, arg2);
            return result;
        }
    }
    async saveReportGlobalInputs(arg0: bigint, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveReportGlobalInputs(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveReportGlobalInputs(arg0, arg1, arg2);
            return result;
        }
    }
    async updateAssessmentStatus(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAssessmentStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAssessmentStatus(arg0, arg1);
            return result;
        }
    }
    async updateAssessmentStep(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAssessmentStep(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAssessmentStep(arg0, arg1);
            return result;
        }
    }
    async updateProjectEvidence(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProjectEvidence(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProjectEvidence(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
