/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AssessmentPlan {
    id: bigint;
    status: string;
    scheduledDate: Time;
    planDetails: string;
    assessmentId: bigint;
}
export type Time = bigint;
export interface Assessment {
    id: bigint;
    status: string;
    name: string;
    createdAt: Time;
    description: string;
}
export interface AssessmentResult {
    id: bigint;
    completedAt: Time;
    recommendations: string;
    score: bigint;
    findings: string;
    assessmentId: bigint;
}
export interface TargetProfile {
    id: bigint;
    name: string;
    criteria: string;
    skillLevel: string;
    assessmentId: bigint;
}
export interface Report {
    id: bigint;
    generatedAt: Time;
    reportContent: string;
    assessmentId: bigint;
}
export interface WorkProduct {
    id: bigint;
    name: string;
    fileType: string;
    notes: string;
    assessmentId: bigint;
    uploadedAt: Time;
}
export interface backendInterface {
    addAssessmentResult(assessmentId: bigint, score: bigint, findings: string, recommendations: string): Promise<bigint>;
    addWorkProduct(assessmentId: bigint, name: string, fileType: string, notes: string): Promise<bigint>;
    createAssessment(name: string, description: string, status: string): Promise<bigint>;
    createAssessmentPlan(assessmentId: bigint, planDetails: string, scheduledDate: Time, status: string): Promise<bigint>;
    createTargetProfile(assessmentId: bigint, name: string, criteria: string, skillLevel: string): Promise<bigint>;
    deleteAssessment(id: bigint): Promise<void>;
    generateReport(assessmentId: bigint, reportContent: string): Promise<bigint>;
    getAllAssessmentPlans(): Promise<Array<AssessmentPlan>>;
    getAllAssessmentResults(): Promise<Array<AssessmentResult>>;
    getAllAssessments(): Promise<Array<Assessment>>;
    getAllReports(): Promise<Array<Report>>;
    getAllTargetProfiles(): Promise<Array<TargetProfile>>;
    getAllWorkProducts(): Promise<Array<WorkProduct>>;
    getAssessment(id: bigint): Promise<Assessment>;
    getAssessmentPlan(id: bigint): Promise<AssessmentPlan>;
    getAssessmentResult(id: bigint): Promise<AssessmentResult>;
    getReport(id: bigint): Promise<Report>;
    getTargetProfile(id: bigint): Promise<TargetProfile>;
    getWorkProduct(id: bigint): Promise<WorkProduct>;
    updateAssessment(id: bigint, name: string, description: string, status: string): Promise<void>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAssessmentResult(arg0: bigint, arg1: bigint, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addAssessmentResult(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAssessmentResult(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addWorkProduct(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addWorkProduct(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWorkProduct(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createAssessment(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createAssessment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAssessment(arg0, arg1, arg2);
            return result;
        }
    }
    async createAssessmentPlan(arg0: bigint, arg1: string, arg2: Time, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createAssessmentPlan(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAssessmentPlan(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createTargetProfile(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTargetProfile(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTargetProfile(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async deleteAssessment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAssessment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAssessment(arg0);
            return result;
        }
    }
    async generateReport(arg0: bigint, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.generateReport(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateReport(arg0, arg1);
            return result;
        }
    }
    async getAllAssessmentPlans(): Promise<Array<AssessmentPlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAssessmentPlans();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAssessmentPlans();
            return result;
        }
    }
    async getAllAssessmentResults(): Promise<Array<AssessmentResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAssessmentResults();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAssessmentResults();
            return result;
        }
    }
    async getAllAssessments(): Promise<Array<Assessment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAssessments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAssessments();
            return result;
        }
    }
    async getAllReports(): Promise<Array<Report>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReports();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReports();
            return result;
        }
    }
    async getAllTargetProfiles(): Promise<Array<TargetProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTargetProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTargetProfiles();
            return result;
        }
    }
    async getAllWorkProducts(): Promise<Array<WorkProduct>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWorkProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWorkProducts();
            return result;
        }
    }
    async getAssessment(arg0: bigint): Promise<Assessment> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssessment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssessment(arg0);
            return result;
        }
    }
    async getAssessmentPlan(arg0: bigint): Promise<AssessmentPlan> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssessmentPlan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssessmentPlan(arg0);
            return result;
        }
    }
    async getAssessmentResult(arg0: bigint): Promise<AssessmentResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssessmentResult(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssessmentResult(arg0);
            return result;
        }
    }
    async getReport(arg0: bigint): Promise<Report> {
        if (this.processError) {
            try {
                const result = await this.actor.getReport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReport(arg0);
            return result;
        }
    }
    async getTargetProfile(arg0: bigint): Promise<TargetProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getTargetProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTargetProfile(arg0);
            return result;
        }
    }
    async getWorkProduct(arg0: bigint): Promise<WorkProduct> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkProduct(arg0);
            return result;
        }
    }
    async updateAssessment(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAssessment(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAssessment(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
